authentication:
  instanceHostname: "nijimiss.moe" # Hostname of the instance
  instanceToken: ""

function:
  reportWatcher: true
  accountLinker: true
  roleSynchronizer: true # Requires accountLinker to be enabled

debug: false
