authentication:
  instanceHostname: "nijimiss.moe" # Hostname of the instance
  instanceToken: ""
  superUserRoleIds: [ ] # ID of the Discord role that can perform all operations

function:
  reportWatcher: true
  accountLinker: true
  roleSynchronizer: true # Requires accountLinker to be enabled
  emojiManager: true # Requires accountLinker to be enabled

debug: false
