authentication:
  instanceHostname: "nijimiss.moe" # Hostname of the instance
  instanceToken: ""

discord:
  targetGuild: 0 # Target guild ID

function:
  reportWatcher: true

debug: false
